supply_chain_dbt:            # must match dbt_project.yml: `profile: supply_chain_dbt`
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /usr/local/airflow/include/google-credentials.json
      project: supply-chain-project-476405
      dataset: supply_chain
      location: US
      threads: 4
      timeout_seconds: 300
